<a href="https://colab.research.google.com/github/ibrohim747/pandas_exercises/blob/main/Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [ ]:
g = np.random.default_rng(0)
month = "Sep Oct Nov Dec Jan Feb Mar Apr May Jun".split()
s = Series(g.integers(40, 60, 10), index = month)
s

Sep    57
Oct    52
Nov    50
Dec    45
Jan    46
Feb    40
Mar    41
Apr    40
May    43
Jun    56
dtype: int64

In [ ]:
print(s.mean(), s.std())
for i in s.index:
  different = 80 - s.mean()
  s[i] = s[i] + different

47.0 6.411794687223781

/tmp/ipykernel_293/1346561519.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '81.7' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  s[i] = s[i] + different

In [ ]:
s

Sep    90.000000
Oct    81.700000
Nov    76.730000
Dec    69.057000
Jan    67.651300
Feb    59.486170
Mar    58.537553
Apr    55.783798
May    57.205418
Jun    68.784876
dtype: float64

In [ ]:
s[s > s.mean() + s.std()]

Sep    90.0
Oct    81.7
dtype: float64

In [ ]:
s[(s < s.mean() + s.std()) & (s > s.mean())]

Nov    76.730000
Dec    69.057000
Jun    68.784876
dtype: float64

In [ ]:
s[(s > s.mean() - s.std()) & (s < s.mean())]

Jan    67.651300
Feb    59.486170
Mar    58.537553
May    57.205418
dtype: float64

In [ ]:
s[s < s.mean() - s.std()]

Apr    55.783798
dtype: float64

In [ ]:
s[(s < s.mean() - 2*s.std()) |  (s > s.mean() + 2*s.std())]

Series([], dtype: float64)

In [ ]:
s.mean()

np.float64(68.4936114767)

In [ ]:
s.median()

68.21808806850001